### ISSUE TITLE
 Encountered an unexpected exception: Vampire Abilities? [Fabric 1.21.1 on 016.9]

### ISSUE THREAD

**Issue by suerion** [mrsterner/witchery#13]
Hey, i had tested the Modpack from me again, after adding the Accessory mod, it does load without issues, but i was slained grom an Healthy Stray and then the Server crash with this error:
```
[15:56:43] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void dev.architectury.networking.NetworkManager.sendToServer(net.minecraft.class_8710)'
	at knot/dev.sterner.witchery.handler.vampire.VampireAbilities.setAbilityIndex(VampireAbilities.java:95) ~[witchery-fabric-0.2.0c.jar:?]
	at knot/dev.sterner.witchery.Witchery.init$lambda$0(Witchery.java:175) ~[witchery-fabric-0.2.0c.jar:?]
	at knot/net.minecraft.class_3324.handler$zlk000$architectury$respawn(MixinPlayerList.java:4019) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.method_14556(MixinPlayerList.java:530) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12068(class_3244.java:1672) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2799.method_12120(class_2799.java:32) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2799.method_11054(class_2799.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Crash Log:
https://mclo.gs/uWet98e

Latest Log Server:
https://mclo.gs/LNIfNkw

**Comment by mrsterner** [comment]
Thank you, i will fix this when i get home
